export NAME := 'grabit'
export APPID := 'io.github.idominikos.Grabit'
export EXTENSION := 'grabit@grabit.local'

rootdir := ''
prefix := '/usr'
debug := '0'

base-dir := absolute_path(clean(rootdir / prefix))
cargo-target-dir := env('CARGO_TARGET_DIR', 'target')
profile := if debug == '1' { 'debug' } else { 'release' }

bin-src := cargo-target-dir / profile / NAME
bin-dst := base-dir / 'bin' / NAME
actions-dst := base-dir / 'share' / NAME / 'actions'
service-dst := base-dir / 'lib' / 'systemd' / 'user' / (NAME + '.service')

# Generated by build.rs from resources/ and the Fluent catalogue in i18n/.
desktop-src := cargo-target-dir / 'xdgen' / 'app.desktop'
desktop-dst := absolute_path(clean(rootdir / 'etc')) / 'xdg' / 'autostart' / (APPID + '.desktop')
metainfo-src := cargo-target-dir / 'xdgen' / 'app.metainfo.xml'
metainfo-dst := base-dir / 'share' / 'metainfo' / (APPID + '.metainfo.xml')

# GNOME Shell extensions are per-user, never system packages.
extension-dst := env('HOME') / '.local' / 'share' / 'gnome-shell' / 'extensions' / EXTENSION

# Default recipe, which runs `just build-release`.
default: build-release

# Runs `cargo clean`.
clean:
    cargo clean

# Compiles with the debug profile.
build-debug *args:
    cargo build {{args}}

# Compiles with the release profile.
build-release *args: (build-debug '--release' args)

# Runs the test suite and a strict clippy pass.
check *args:
    cargo test {{args}}
    cargo clippy --all-targets {{args}} -- -D warnings

# Builds and runs the daemon with debug logging.
run: build-release
    env RUST_LOG=grabit=debug {{bin-src}} run

# Reports what the current session supports.
doctor: build-release
    {{bin-src}} doctor

# Installs the daemon, its packaged actions and its XDG metadata.
install: build-release
    install -Dm0755 {{bin-src}} {{bin-dst}}
    install -d {{actions-dst}}
    install -Dm0644 actions/*.toml -t {{actions-dst}}
    install -Dm0644 {{desktop-src}} {{desktop-dst}}
    install -Dm0644 {{metainfo-src}} {{metainfo-dst}}
    install -Dm0644 data/grabit.service {{service-dst}}

# Installs the GNOME Shell extension into the current user's home. GNOME only.
install-extension:
    install -d {{extension-dst}}
    install -Dm0644 gnome-extension/{{EXTENSION}}/* -t {{extension-dst}}
    @echo 'Log out and back in, then: gnome-extensions enable {{EXTENSION}}'

# Removes everything `install` and `install-extension` put down.
uninstall:
    rm -f {{bin-dst}} {{desktop-dst}} {{metainfo-dst}} {{service-dst}}
    rm -rf {{base-dir}}/share/{{NAME}}
    rm -rf {{extension-dst}}
